package com.synereo.ltcctbc.frugl.Absyn; // Java Package generated by the BNF Converter.

public class CutExpression extends CoEquation {
  public final Term term_1, term_2;

  public CutExpression(Term p1, Term p2) { term_1 = p1; term_2 = p2; }

  public <R,A> R accept(com.synereo.ltcctbc.frugl.Absyn.CoEquation.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.synereo.ltcctbc.frugl.Absyn.CutExpression) {
      com.synereo.ltcctbc.frugl.Absyn.CutExpression x = (com.synereo.ltcctbc.frugl.Absyn.CutExpression)o;
      return this.term_1.equals(x.term_1) && this.term_2.equals(x.term_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.term_1.hashCode())+this.term_2.hashCode();
  }


}
