package com.synereo.ltcctbc.frugl.Absyn; // Java Package generated by the BNF Converter.

public class DecimalLiteral extends ValueExpr {
  public final Double double_;

  public DecimalLiteral(Double p1) { double_ = p1; }

  public <R,A> R accept(com.synereo.ltcctbc.frugl.Absyn.ValueExpr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.synereo.ltcctbc.frugl.Absyn.DecimalLiteral) {
      com.synereo.ltcctbc.frugl.Absyn.DecimalLiteral x = (com.synereo.ltcctbc.frugl.Absyn.DecimalLiteral)o;
      return this.double_.equals(x.double_);
    }
    return false;
  }

  public int hashCode() {
    return this.double_.hashCode();
  }


}
