package com.synereo.ltcctbc.frugl.Absyn; // Java Package generated by the BNF Converter.

public class Extraction extends Term {
  public final ListNominal listnominal_;
  public final ListPfExpr listpfexpr_;

  public Extraction(ListNominal p1, ListPfExpr p2) { listnominal_ = p1; listpfexpr_ = p2; }

  public <R,A> R accept(com.synereo.ltcctbc.frugl.Absyn.Term.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.synereo.ltcctbc.frugl.Absyn.Extraction) {
      com.synereo.ltcctbc.frugl.Absyn.Extraction x = (com.synereo.ltcctbc.frugl.Absyn.Extraction)o;
      return this.listnominal_.equals(x.listnominal_) && this.listpfexpr_.equals(x.listpfexpr_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.listnominal_.hashCode())+this.listpfexpr_.hashCode();
  }


}
