package com.synereo.ltcctbc.frugl.Absyn; // Java Package generated by the BNF Converter.

public class FoundationType extends LTyp {
  public final GroundType groundtype_;

  public FoundationType(GroundType p1) { groundtype_ = p1; }

  public <R,A> R accept(com.synereo.ltcctbc.frugl.Absyn.LTyp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.synereo.ltcctbc.frugl.Absyn.FoundationType) {
      com.synereo.ltcctbc.frugl.Absyn.FoundationType x = (com.synereo.ltcctbc.frugl.Absyn.FoundationType)o;
      return this.groundtype_.equals(x.groundtype_);
    }
    return false;
  }

  public int hashCode() {
    return this.groundtype_.hashCode();
  }


}
