package com.synereo.ltcctbc.frugl.Absyn; // Java Package generated by the BNF Converter.

public abstract class GroundType implements java.io.Serializable {
  public abstract <R,A> R accept(GroundType.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(com.synereo.ltcctbc.frugl.Absyn.UserDefinedType p, A arg);
    public R visit(com.synereo.ltcctbc.frugl.Absyn.IntegerType p, A arg);
    public R visit(com.synereo.ltcctbc.frugl.Absyn.DoubleType p, A arg);
    public R visit(com.synereo.ltcctbc.frugl.Absyn.StringType p, A arg);
    public R visit(com.synereo.ltcctbc.frugl.Absyn.UnitType p, A arg);
    public R visit(com.synereo.ltcctbc.frugl.Absyn.VoidType p, A arg);
    public R visit(com.synereo.ltcctbc.frugl.Absyn.BTCType p, A arg);

  }

}
