package com.synereo.ltcctbc.frugl.Absyn; // Java Package generated by the BNF Converter.

public class Indication extends FormalExpr {
  public final Nominal nominal_;

  public Indication(Nominal p1) { nominal_ = p1; }

  public <R,A> R accept(com.synereo.ltcctbc.frugl.Absyn.FormalExpr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.synereo.ltcctbc.frugl.Absyn.Indication) {
      com.synereo.ltcctbc.frugl.Absyn.Indication x = (com.synereo.ltcctbc.frugl.Absyn.Indication)o;
      return this.nominal_.equals(x.nominal_);
    }
    return false;
  }

  public int hashCode() {
    return this.nominal_.hashCode();
  }


}
