package com.synereo.ltcctbc.frugl.Absyn; // Java Package generated by the BNF Converter.

public class InjectionLeft extends Term {
  public final Term term_;

  public InjectionLeft(Term p1) { term_ = p1; }

  public <R,A> R accept(com.synereo.ltcctbc.frugl.Absyn.Term.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.synereo.ltcctbc.frugl.Absyn.InjectionLeft) {
      com.synereo.ltcctbc.frugl.Absyn.InjectionLeft x = (com.synereo.ltcctbc.frugl.Absyn.InjectionLeft)o;
      return this.term_.equals(x.term_);
    }
    return false;
  }

  public int hashCode() {
    return this.term_.hashCode();
  }


}
