package com.synereo.ltcctbc.frugl.Absyn; // Java Package generated by the BNF Converter.

public class IntegerLiteral extends ValueExpr {
  public final Integer integer_;

  public IntegerLiteral(Integer p1) { integer_ = p1; }

  public <R,A> R accept(com.synereo.ltcctbc.frugl.Absyn.ValueExpr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.synereo.ltcctbc.frugl.Absyn.IntegerLiteral) {
      com.synereo.ltcctbc.frugl.Absyn.IntegerLiteral x = (com.synereo.ltcctbc.frugl.Absyn.IntegerLiteral)o;
      return this.integer_.equals(x.integer_);
    }
    return false;
  }

  public int hashCode() {
    return this.integer_.hashCode();
  }


}
