package com.synereo.ltcctbc.frugl.Absyn; // Java Package generated by the BNF Converter.

public abstract class LTyp implements java.io.Serializable {
  public abstract <R,A> R accept(LTyp.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(com.synereo.ltcctbc.frugl.Absyn.ImplicationType p, A arg);
    public R visit(com.synereo.ltcctbc.frugl.Absyn.ExplicationType p, A arg);
    public R visit(com.synereo.ltcctbc.frugl.Absyn.FusionType p, A arg);
    public R visit(com.synereo.ltcctbc.frugl.Absyn.SeparationType p, A arg);
    public R visit(com.synereo.ltcctbc.frugl.Absyn.SelectionType p, A arg);
    public R visit(com.synereo.ltcctbc.frugl.Absyn.ConfirmationType p, A arg);
    public R visit(com.synereo.ltcctbc.frugl.Absyn.DurationType p, A arg);
    public R visit(com.synereo.ltcctbc.frugl.Absyn.ReplicationType p, A arg);
    public R visit(com.synereo.ltcctbc.frugl.Absyn.NegationType p, A arg);
    public R visit(com.synereo.ltcctbc.frugl.Absyn.FoundationType p, A arg);

  }

}
