package com.synereo.ltcctbc.frugl.Absyn; // Java Package generated by the BNF Converter.

public class Mention extends Term {
  public final FormalExpr formalexpr_;

  public Mention(FormalExpr p1) { formalexpr_ = p1; }

  public <R,A> R accept(com.synereo.ltcctbc.frugl.Absyn.Term.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.synereo.ltcctbc.frugl.Absyn.Mention) {
      com.synereo.ltcctbc.frugl.Absyn.Mention x = (com.synereo.ltcctbc.frugl.Absyn.Mention)o;
      return this.formalexpr_.equals(x.formalexpr_);
    }
    return false;
  }

  public int hashCode() {
    return this.formalexpr_.hashCode();
  }


}
