package com.synereo.ltcctbc.frugl.Absyn; // Java Package generated by the BNF Converter.

public class ProofExpression extends PfExpr {
  public final ListTerm listterm_;
  public final ListCoEquation listcoequation_;

  public ProofExpression(ListTerm p1, ListCoEquation p2) { listterm_ = p1; listcoequation_ = p2; }

  public <R,A> R accept(com.synereo.ltcctbc.frugl.Absyn.PfExpr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.synereo.ltcctbc.frugl.Absyn.ProofExpression) {
      com.synereo.ltcctbc.frugl.Absyn.ProofExpression x = (com.synereo.ltcctbc.frugl.Absyn.ProofExpression)o;
      return this.listterm_.equals(x.listterm_) && this.listcoequation_.equals(x.listcoequation_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.listterm_.hashCode())+this.listcoequation_.hashCode();
  }


}
