package com.synereo.ltcctbc.frugl.Absyn; // Java Package generated by the BNF Converter.

public class Selection extends Term {
  public final ListNominal listnominal_;
  public final PfExpr pfexpr_1, pfexpr_2;

  public Selection(ListNominal p1, PfExpr p2, PfExpr p3) { listnominal_ = p1; pfexpr_1 = p2; pfexpr_2 = p3; }

  public <R,A> R accept(com.synereo.ltcctbc.frugl.Absyn.Term.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.synereo.ltcctbc.frugl.Absyn.Selection) {
      com.synereo.ltcctbc.frugl.Absyn.Selection x = (com.synereo.ltcctbc.frugl.Absyn.Selection)o;
      return this.listnominal_.equals(x.listnominal_) && this.pfexpr_1.equals(x.pfexpr_1) && this.pfexpr_2.equals(x.pfexpr_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.listnominal_.hashCode())+this.pfexpr_1.hashCode())+this.pfexpr_2.hashCode();
  }


}
