package com.synereo.ltcctbc.frugl.Absyn; // Java Package generated by the BNF Converter.

public abstract class Term implements java.io.Serializable {
  public abstract <R,A> R accept(Term.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(com.synereo.ltcctbc.frugl.Absyn.Fusion p, A arg);
    public R visit(com.synereo.ltcctbc.frugl.Absyn.Separation p, A arg);
    public R visit(com.synereo.ltcctbc.frugl.Absyn.Duplication p, A arg);
    public R visit(com.synereo.ltcctbc.frugl.Absyn.Selection p, A arg);
    public R visit(com.synereo.ltcctbc.frugl.Absyn.Duration p, A arg);
    public R visit(com.synereo.ltcctbc.frugl.Absyn.InjectionLeft p, A arg);
    public R visit(com.synereo.ltcctbc.frugl.Absyn.InjectionRight p, A arg);
    public R visit(com.synereo.ltcctbc.frugl.Absyn.Extraction p, A arg);
    public R visit(com.synereo.ltcctbc.frugl.Absyn.Mention p, A arg);
    public R visit(com.synereo.ltcctbc.frugl.Absyn.Value p, A arg);

  }

}
