package com.synereo.ltcctbc.frugl.Absyn; // Java Package generated by the BNF Converter.

public class Transcription extends Nominal {
  public final PfExpr pfexpr_;

  public Transcription(PfExpr p1) { pfexpr_ = p1; }

  public <R,A> R accept(com.synereo.ltcctbc.frugl.Absyn.Nominal.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.synereo.ltcctbc.frugl.Absyn.Transcription) {
      com.synereo.ltcctbc.frugl.Absyn.Transcription x = (com.synereo.ltcctbc.frugl.Absyn.Transcription)o;
      return this.pfexpr_.equals(x.pfexpr_);
    }
    return false;
  }

  public int hashCode() {
    return this.pfexpr_.hashCode();
  }


}
