package com.synereo.ltcctbc.frugl.Absyn; // Java Package generated by the BNF Converter.

public class TypeAssignment extends TypedTerm {
  public final Term term_;
  public final LTyp ltyp_;

  public TypeAssignment(Term p1, LTyp p2) { term_ = p1; ltyp_ = p2; }

  public <R,A> R accept(com.synereo.ltcctbc.frugl.Absyn.TypedTerm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.synereo.ltcctbc.frugl.Absyn.TypeAssignment) {
      com.synereo.ltcctbc.frugl.Absyn.TypeAssignment x = (com.synereo.ltcctbc.frugl.Absyn.TypeAssignment)o;
      return this.term_.equals(x.term_) && this.ltyp_.equals(x.ltyp_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.term_.hashCode())+this.ltyp_.hashCode();
  }


}
