package com.synereo.ltcctbc.frugl.Absyn; // Java Package generated by the BNF Converter.

public class TypeJudgment extends TypedExpr {
  public final ListTypedTerm listtypedterm_;
  public final ListCoEquation listcoequation_;

  public TypeJudgment(ListTypedTerm p1, ListCoEquation p2) { listtypedterm_ = p1; listcoequation_ = p2; }

  public <R,A> R accept(com.synereo.ltcctbc.frugl.Absyn.TypedExpr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.synereo.ltcctbc.frugl.Absyn.TypeJudgment) {
      com.synereo.ltcctbc.frugl.Absyn.TypeJudgment x = (com.synereo.ltcctbc.frugl.Absyn.TypeJudgment)o;
      return this.listtypedterm_.equals(x.listtypedterm_) && this.listcoequation_.equals(x.listcoequation_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.listtypedterm_.hashCode())+this.listcoequation_.hashCode();
  }


}
