package com.synereo.ltcctbc.frugl.Absyn; // Java Package generated by the BNF Converter.

public class UserDefinedType extends GroundType {
  public final String uident_;

  public UserDefinedType(String p1) { uident_ = p1; }

  public <R,A> R accept(com.synereo.ltcctbc.frugl.Absyn.GroundType.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.synereo.ltcctbc.frugl.Absyn.UserDefinedType) {
      com.synereo.ltcctbc.frugl.Absyn.UserDefinedType x = (com.synereo.ltcctbc.frugl.Absyn.UserDefinedType)o;
      return this.uident_.equals(x.uident_);
    }
    return false;
  }

  public int hashCode() {
    return this.uident_.hashCode();
  }


}
