package com.synereo.ltcctbc.frugl.Absyn; // Java Package generated by the BNF Converter.

public abstract class ValueExpr implements java.io.Serializable {
  public abstract <R,A> R accept(ValueExpr.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(com.synereo.ltcctbc.frugl.Absyn.DecimalLiteral p, A arg);
    public R visit(com.synereo.ltcctbc.frugl.Absyn.IntegerLiteral p, A arg);
    public R visit(com.synereo.ltcctbc.frugl.Absyn.StringLiteral p, A arg);
    public R visit(com.synereo.ltcctbc.frugl.Absyn.UnitLiteral p, A arg);
    public R visit(com.synereo.ltcctbc.frugl.Absyn.CoUnitLiteral p, A arg);
    public R visit(com.synereo.ltcctbc.frugl.Absyn.BTCUnitLiteral p, A arg);

  }

}
